/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.UserController;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LoginView extends javax.swing.JInternalFrame {
    private UserController userController;
     javax.swing.JMenuItem mnJob;
    public javax.swing.JMenuItem mnRegion;
    /**
     * Creates new form LoginView
     */
    public LoginView(JMenuItem mnJob, JMenuItem mnRegion) {
        initComponents();
        this.userController = new UserController();
        this.mnJob = mnJob;
        this.mnRegion = mnRegion;     
    }
    
    public LoginView() {
        initComponents();
        this.userController = new UserController();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        pasField = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        labForgot = new javax.swing.JLabel();

        setTitle("Login");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        pasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasFieldActionPerformed(evt);
            }
        });
        pasField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pasFieldKeyPressed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Username :");

        jLabel2.setText("Password :");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        labForgot.setText("Forgot your password ? Click here");
        labForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labForgotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pasField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(158, 158, 158)))
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labForgot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnRegister))
                .addGap(26, 26, 26)
                .addComponent(labForgot)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText();
        String password = String.valueOf(pasField.getPassword());
        boolean login = this.userController.LoginUser(username, password);
        String msg = "";
        if (login) {
            msg = "Berhasil Login";
            JOptionPane.showMessageDialog(this, msg);
            txtUsername.setText("");
            pasField.setText("");
            this.dispose();
            this.mnJob.setEnabled(true);
            this.mnRegion.setEnabled(true);
        }else{
            msg = "Username atau password salah";
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        this.mnJob.setEnabled(false);
        this.mnRegion.setEnabled(false);
        RegisterView registerView = new RegisterView(mnJob, mnRegion);
        registerView.show();
        this.getDesktopPane().add(registerView);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void pasFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pasFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String username = txtUsername.getText();
            String password = String.valueOf(pasField.getPassword());
            boolean login = this.userController.LoginUser(username, password);
            String msg = "";
            if (login) {
                msg = "Berhasil Login";
                JOptionPane.showMessageDialog(this, msg);
                txtUsername.setText("");
                pasField.setText("");
                this.dispose();
                this.mnJob.setEnabled(true);
                this.mnRegion.setEnabled(true);
            }else{
                msg = "Username atau password salah";
                JOptionPane.showMessageDialog(this, msg);
            }
        }
    }//GEN-LAST:event_pasFieldKeyPressed

    private void labForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labForgotMouseClicked
        ForgotView forgotView = new ForgotView();
        forgotView.show();
        this.getDesktopPane().add(forgotView);
        this.dispose();
    }//GEN-LAST:event_labForgotMouseClicked

    private void pasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labForgot;
    private javax.swing.JPasswordField pasField;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
