/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.UserController;
import java.awt.event.KeyEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VerificationView extends javax.swing.JInternalFrame {
    private UserController userController;
    String username;
    int id;
    Boolean prevView;
    public javax.swing.JMenuItem mnJob;
    public javax.swing.JMenuItem mnRegion;
    /** 
     * Creates new form VerificationViewFikri
     */
    public VerificationView(String userTxt) {
        initComponents();
        this.userController = new UserController();
        this.username = userTxt;
    }
    
    public VerificationView(String userTxt, int id, boolean pervView,JMenuItem mnJob, JMenuItem mnRegion){
        initComponents();
        this.userController = new UserController();
        this.username = userTxt;
        this.id = id;
        this.prevView = pervView;
        System.out.println(prevView);
        labUser.setText("Welcome "+userTxt+", please insert code");
        this.mnJob = mnJob;
        this.mnRegion = mnRegion;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVerification = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        labUser = new javax.swing.JLabel();

        setTitle("Verification");

        txtVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerificationActionPerformed(evt);
            }
        });
        txtVerification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVerificationKeyPressed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        btnSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSendKeyPressed(evt);
            }
        });

        labUser.setText("username Text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtVerification, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(labUser)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVerification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSend)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerificationActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        String code = txtVerification.getText();
        String newId = id+"";
        if (CheckCode(code,newId)) {
            JOptionPane.showMessageDialog(this, "Verfikasi akun berhasil");
            if (prevView) {
                NewPasswordView newPassword = new NewPasswordView(newId,mnJob, mnRegion);
                newPassword.show();
                this.getDesktopPane().add(newPassword);
            }else{
                LoginView view = new LoginView(mnJob, mnRegion);
                view.show();
                this.getDesktopPane().add(view);
            }
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Kode salah. Masukkan code yang tepat");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSendKeyPressed

    }//GEN-LAST:event_btnSendKeyPressed

    private void txtVerificationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerificationKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String code = txtVerification.getText();
            String newId = id+"";
            boolean verifResult = userController.verficationUser(code,newId);
            if (verifResult) {
                JOptionPane.showMessageDialog(this, "Verfikasi akun berhasil");
                if ( id != 0) {
                    NewPasswordView newPassword = new NewPasswordView();
                    newPassword.show();
                    this.getDesktopPane().add(newPassword);
                }
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Kode salah. Masukkan code yang tepat");
            }
        }
    }//GEN-LAST:event_txtVerificationKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel labUser;
    private javax.swing.JTextField txtVerification;
    // End of variables declaration//GEN-END:variables

private boolean CheckCode(String code,String id) {
        return userController.verficationUser(code,id);   
    }
}
